#!/bin/bash

check_package(){
dpkg -s $1 > /dev/null

if [ $? -eq 0 ]; then
    echo "$1 is installed!"
else
    >&2 echo "$1 is NOT installed!"
    exit 0
fi
}

check_package curl
check_package nmap
check_package hydra
check_package xmlstarlet
exit 0
